给safe.cgi和victim.cgi增加可执行权限
vulhub/vulhub pull request #423
Opened 2023-04-22 14:38 UTC by y4ney

解决请求safe.cgi和victim.cgi时，服务器出现错误的问题，问题如#422 所示。分析如下所示：
- 首先，我们进入容器查看Apache的错误日志，发现是两个cgi的权限不够

```Bash
cat /var/log/apache2/error.log
```

```Verilog
[Tue Apr 18 15:53:16.186480 2023] [cgid:error] [pid 74:tid 274932278848] (13)Permission denied: AH01241: exec of '/var/www/html/victim.cgi' failed
[Tue Apr 18 15:53:16.194556 2023] [cgid:error] [pid 16:tid 275190703872] [client 172.21.0.1:52124] End of script output before headers: victim.cgi
```

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/44939500/233790867-4a437e2c-66e1-499b-a3b6-7fe3a479878f.png">

- 然后，我们退出容器，给两个文件赋予执行权限

```Bash
chmod +x ./victim.cgi && chmod +x ./safe.cgi
```
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/44939500/233790899-fbd3b792-90a9-4a19-84e4-30288ad1179e.png">

- 最后，我们再次访问`http://your-ip:8080/victim.cgi`和`http://your-ip:8080/safe.cgi`，发现修改生效，可成功访问
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/44939500/233790925-ded3d481-17ee-4de6-9232-46f1eadc913f.png">

2023-04-28 16:48 UTC, phith0n requested changes

2023-04-28 16:48 UTC, phith0n commented on docker/unauthorized-rce/docker-compose.yml
> +   platform: linux/amd64
无关的代码修改可以去掉

2023-04-28 16:48 UTC, phith0n commented on bash/CVE-2014-6271/docker-compose.yml
> +    - ./victim.cgi:/var/www/html/victim.cgi
同理，这块的代码修改没有必要，本地测试即可~

2023-04-29 02:16 UTC, y4ney commented
可能是我不小心把本地测试代码给提交上去了😂

2023-04-29 02:40 UTC, y4ney commented
我已经revert到正确的commit了

2023-05-04 03:27 UTC, phith0n commented
你把该提交的部分去掉了，把该留下的部分提交了。。。

2023-05-11 06:22 UTC, closed without merging

2023-05-11 06:28 UTC, phith0n commented
帮你改了：<https://github.com/vulhub/vulhub/pull/429>

2023-05-11 06:47 UTC, y4ney commented
谢谢呀，不好意思给你带来麻烦了